apiVersion: v1
kind: Namespace
metadata:
  name: aion-cr
  labels:
    name: aion-cr
    env: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: aion-cr-monitoring
  labels:
    name: aion-cr-monitoring
    env: production